import streamlit as st
import pandas as pd
import numpy as np
import joblib

# ── Page Config ──────────────────────────────────────────────
st.set_page_config(
    page_title="Loan Approval Predictor",
    page_icon="🏦",
    layout="centered"
)

st.title("🏦 Loan Approval Prediction")
st.markdown("Enter applicant details below to predict loan approval likelihood.")

# ── Load Artifacts ───────────────────────────────────────────
@st.cache_resource
def load_artifacts():
    model    = joblib.load("saved_model/best_model.pkl")
    scaler   = joblib.load("saved_model/scaler.pkl")
    features = joblib.load("saved_model/feature_names.pkl")
    mappings = joblib.load("saved_model/label_mappings.pkl")
    return model, scaler, features, mappings

model, scaler, feature_names, label_mappings = load_artifacts()

# ── Input Form ───────────────────────────────────────────────
st.subheader("Applicant Information")
col1, col2 = st.columns(2)

with col1:
    age           = st.number_input("Age", 18, 80, 30)
    income        = st.number_input("Annual Income ($)", 5000, 500000, 50000, step=1000)
    loan_amnt     = st.number_input("Loan Amount ($)", 500, 100000, 10000, step=500)
    loan_int_rate = st.number_input("Interest Rate (%)", 1.0, 30.0, 12.0, step=0.1)

with col2:
    loan_pct_income = st.slider("Loan % of Income", 0.0, 1.0, 0.2, step=0.01)
    cred_hist       = st.number_input("Credit History Length (years)", 0, 30, 5)
    prev_default    = st.selectbox("Previous Loan Default?", ["No", "Yes"])
    loan_intent     = st.selectbox("Loan Intent", list(label_mappings.get("loan_intent", {"PERSONAL": 0}).keys()))
    person_gender   = st.selectbox("Gender", list(label_mappings.get("person_gender", {"male": 0}).keys()))
    education       = st.selectbox("Education", list(label_mappings.get("person_education", {"Bachelor": 0}).keys()))

# ── Predict ──────────────────────────────────────────────────
if st.button("🔍 Predict Loan Approval", type="primary"):
    input_data = {
        "person_age":                     age,
        "person_income":                  np.log1p(income),
        "person_gender":                  label_mappings.get("person_gender", {}).get(person_gender, 0),
        "person_education":               label_mappings.get("person_education", {}).get(education, 0),
        "loan_amnt":                      np.log1p(loan_amnt),
        "loan_intent":                    label_mappings.get("loan_intent", {}).get(loan_intent, 0),
        "loan_int_rate":                  loan_int_rate,
        "loan_percent_income":            np.log1p(loan_pct_income),
        "cb_person_cred_hist_length":     cred_hist,
        "previous_loan_defaults_on_file": 1 if prev_default == "Yes" else 0,
        "debt_to_income_ratio":           loan_amnt / (income + 1),
        "income_per_age":                 income / (age + 1),
        "loan_to_credit_hist":            loan_amnt / (cred_hist + 1),
        "is_high_loan":                   1 if loan_amnt > 25000 else 0,
        "is_high_income":                 1 if income > 60000 else 0,
    }

    input_df     = pd.DataFrame([input_data])
    input_df     = input_df.reindex(columns=feature_names, fill_value=0)
    input_scaled = scaler.transform(input_df)
    prediction   = model.predict(input_scaled)[0]
    probability  = model.predict_proba(input_scaled)[0][1]

    st.divider()
    if prediction == 1:
        st.success(f"✅ **APPROVED** — Approval Probability: {probability*100:.1f}%")
    else:
        st.error(f"❌ **REJECTED** — Approval Probability: {probability*100:.1f}%")
    st.progress(float(probability))
    st.caption("This prediction is generated by a machine learning model and should be used as a supporting tool only.")
